version: '3'

services:
  auction-api:
    image: auction-api
    pull_policy: never
    restart: always
    container_name: auction-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auction-api.rule=Host(`api-leilao.thiagosol.com`)"
      - "traefik.http.routers.auction-api.entrypoints=https"
      - "traefik.http.routers.auction-api.tls=true"
      - "traefik.http.services.auction-api.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=auction-api,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    environment:
      - RUST_LOG=info
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
