version: '3'

services:
  auction-api:
    image: auction-api
    pull_policy: never
    restart: always
    container_name: auction-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auction-api.entrypoints=http"
      - "traefik.http.routers.auction-api.rule=Host(`api.leilao.thiagosol.com`) || Host(`www.api.leilao.thiagosol.com`)"
      - "traefik.http.routers.auction-api-secure.entrypoints=https"
      - "traefik.http.routers.auction-api-secure.rule=Host(`api.leilao.thiagosol.com`) || Host(`www.api.leilao.thiagosol.com`)"
      - "traefik.http.routers.auction-api-secure.tls=true"
      - "traefik.http.routers.auction-api-secure.service=auction-api-secure"
      - "traefik.http.services.auction-api-secure.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    environment:
      - RUST_LOG=info
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  default:
    external:
      name: external-sol-apis
