version: '3'

services:
  auction-api:
    image: auction-api
    pull_policy: never
    restart: always
    container_name: auction-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=auction-api,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    environment:
      - RUST_LOG=info
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
